### ISSUE TITLE
`ta start` doesn't start the scoring process

### ISSUE THREAD

**Issue by sirateek** [ta-assistant/TA-CLI#45]
## Step to reproduce
1. `ta start`
2. TA-CLI ask for oepning the VS Code and file extration. Answer `y` to all.
2. The file extraction process successfully to run.
3.  End process without opening any VSCode or asking about the score

## Log
```
 ❯ ta start
Do you want to open vscode?(y/n): y
Folder by folder?(y/n): y
Sucessfully add draft
Your workId is {'prefix': 'https://ta-api.sirateek.dev/', 'workID': 'testWork', 'apikeydir': '/Users/sirateek/key'}
Unzip progress: |████████████████████| 100.0% 6310546063_vitvara_ex1.zip complete

❯ (End Process here)
```

**Comment by vitvara** [comment]
fixed by change the condition in src/run_work.py
